In [1]:
import numpy as np
import scipy.io
import scipy.signal
import matplotlib.pyplot as plt
from datascience import *
import math as m

In [6]:
def PowerLabDataReader (file_name, file_format, RED_offset, NIR_offset, FS_raw, TS):
    file = np.loadtxt(file_name+file_format, delimiter = '\t', skiprows = 6)
    TS_raw = 1/FS_raw # (s/sample)
    LEN = len(file) # length of data

    FS = 1/TS # (sample/s) new sampling frequency

    TIME = np.arange(0,LEN*TS,TS)

    RED_dim = np.arange(m.ceil(RED_offset*FS_raw), LEN, m.ceil(TS*FS_raw))
    NIR_dim = np.arange(m.ceil(NIR_offset*FS_raw), LEN, m.ceil(TS*FS_raw))
    RED_full = file[RED_dim]
    NIR_full = file[NIR_dim]
    
    RED = make_array()

    for i in np.arange(len(RED_full)):
        RED = np.append(RED, RED_full[i][np.arange(1,5)])

    NIR = make_array()

    for i in np.arange(len(NIR_full)):
        NIR = np.append(NIR, NIR_full[i][np.arange(1,5)])
        
    dictionary = {'TIME': TIME, 'NIR': NIR, 'RED': RED}
    
    output = scipy.io.savemat('cycling_4_FunctionTest.mat', dictionary)
    
    return TIME, RED, NIR, output

In [7]:
PowerLabDataReader('cycling_4', '.txt', 0.7e-3, 0.1e-3, 10000, 1.2e-3)

(array([0.0000000e+00, 1.2000000e-03, 2.4000000e-03, ..., 2.1659976e+03,
        2.1659988e+03, 2.1660000e+03]),
 array([412.2188, 413.4063, 436.4375, ..., 405.4688, 434.25  , 454.2188]),
 array([412.125 , 413.3438, 436.5   , ..., 405.4063, 434.25  , 454.25  ]),
 None)